apiVersion: apps/v1
kind: Deployment
metadata:
  name: conductor
  labels:
    app: conductor
spec:
  selector:
    matchLabels:
      app: conductor
  replicas: 1
  template:
    metadata:
      labels:
        app: conductor
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: conductor
          image: docker.io/sholly/servicemesh-conductor:jaeger
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 9779
              name: prometheus
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: openshift
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: conductor
  name: conductor
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
  selector:
    app: conductor
